name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      APP_NAME: Quarantine-Truth-or-Dare
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Node modules
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Docker build
        run: |
          docker build . \
            --tag ${{ env.APP_NAME }}:${{ github.run_number }} \
            --tag ${{ env.APP_NAME }}:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: production
      url: https://quarantine-truth-or-dare.herokuapp.com/
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "quarantine-truth-or-dare"
          heroku_email: "jeffrey@sadeli.com"
